#!/bin/bash

# import_antigravity.sh
# Script to restore Antigravity agent state from antigravity_export.zip
# Generated by Gemini 3 Pro

set -e

EXPORT_FILE="antigravity_export.zip"
TARGET_GEMINI_DIR="$HOME/.gemini"
TEMP_DIR="antigravity_migration_temp"

# colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Starting Antigravity State Import...${NC}"

if [ ! -f "$EXPORT_FILE" ]; then
    echo -e "${RED}Error: $EXPORT_FILE not found in current directory.${NC}"
    exit 1
fi

echo "Cleaning up any previous temp files..."
rm -rf "$TEMP_DIR"
mkdir -p "$TEMP_DIR"

echo "Unzipping export file..."
unzip -q "$EXPORT_FILE" -d "$TEMP_DIR"

# Find the exported .gemini directory inside the zip structure
# It's likely under Users/<username>/.gemini
EXPORTED_GEMINI_PATH=$(find "$TEMP_DIR" -type d -name ".gemini" | head -n 1)

if [ -z "$EXPORTED_GEMINI_PATH" ]; then
    echo -e "${RED}Error: Could not find .gemini directory in export.${NC}"
    exit 1
fi

echo -e "Found exported state at: ${EXPORTED_GEMINI_PATH}"
echo -e "Target directory: ${TARGET_GEMINI_DIR}"

if [ ! -d "$TARGET_GEMINI_DIR" ]; then
    echo "Creating $TARGET_GEMINI_DIR..."
    mkdir -p "$TARGET_GEMINI_DIR"
fi

echo -e "${YELLOW}Merging agent state...${NC}"
# Copy contents recursively
cp -R "$EXPORTED_GEMINI_PATH/"* "$TARGET_GEMINI_DIR/"

echo -e "${GREEN}Success! Agent state imported to $TARGET_GEMINI_DIR${NC}"
echo "Cleaning up temp files..."
rm -rf "$TEMP_DIR"

echo -e "${GREEN}Import Complete.${NC}"
echo "You can now run Antigravity in this project, and it should remember past context."
