<#
.SYNOPSIS
    Imports Antigravity agent state from antigravity_export.zip on Windows.
.DESCRIPTION
    This script extracts the antigravity_export.zip file and restores the 
    Agent's memory and state to the current user's .gemini directory.
    Generated by Gemini 3 Pro.
#>

$ErrorActionPreference = "Stop"

$exportFile = "antigravity_export.zip"
$targetGeminiDir = Join-Path $env:USERPROFILE ".gemini"
$tempDir = "antigravity_migration_temp"

Write-Host "Starting Antigravity State Import on Windows..." -ForegroundColor Yellow

if (-not (Test-Path -Path $exportFile)) {
    Write-Error "Error: $exportFile not found in current directory."
    exit 1
}

# Clean up temp dir
if (Test-Path -Path $tempDir) {
    Remove-Item -Path $tempDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $tempDir | Out-Null

Write-Host "Unzipping export file..."
Expand-Archive -Path $exportFile -DestinationPath $tempDir -Force

# Find the exported .gemini directory (recursively search for brain/conversations parent)
# The zip structure is usually Users/username/.gemini
$exportedGemini = Get-ChildItem -Path $tempDir -Recurse -Directory -Filter ".gemini" | Select-Object -First 1

if ($null -eq $exportedGemini) {
    Write-Error "Error: Could not find .gemini directory in export."
    exit 1
}

Write-Host "Found exported state at: $($exportedGemini.FullName)"
Write-Host "Target directory: $targetGeminiDir"

if (-not (Test-Path -Path $targetGeminiDir)) {
    Write-Host "Creating $targetGeminiDir..."
    New-Item -ItemType Directory -Force -Path $targetGeminiDir | Out-Null
}

Write-Host "Merging agent state..." -ForegroundColor Yellow
# Copy contents recursively
Copy-Item -Path "$($exportedGemini.FullName)\*" -Destination $targetGeminiDir -Recurse -Force

Write-Host "Cleaning up temp files..."
Remove-Item -Path $tempDir -Recurse -Force

Write-Host "Success! Agent state imported to $targetGeminiDir" -ForegroundColor Green
Write-Host "Import Complete."
Write-Host "You can now run Antigravity in this project on Windows."
